# Generated by Django 5.1.2 on 2024-10-21 12:46

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the course.",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the course.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the course was created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the course was last updated.",
                        verbose_name="Updated at",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the chapter.",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the chapter was created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the chapter was last updated.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "chapter_nr",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of the chapter.",
                        null=True,
                        verbose_name="Chapter number",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Course to which the chapter belongs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="learncraft.course",
                        verbose_name="Course",
                    ),
                ),
            ],
            options={
                "unique_together": {("course", "chapter_nr")},
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the section.",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "section_nr",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of the section.",
                        null=True,
                        verbose_name="Section number",
                    ),
                ),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Content"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the section was created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the section was last updated.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        help_text="Chapter to which the section belongs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="learncraft.chapter",
                        verbose_name="Chapter",
                    ),
                ),
            ],
            options={
                "unique_together": {("chapter", "section_nr")},
            },
        ),
    ]
