# Generated by Django 5.1.2 on 2024-10-22 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learncraft", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        help_text="Uploaded video file.",
                        upload_to="videos/",
                        verbose_name="Video",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the video was uploaded.",
                        verbose_name="Uploaded at",
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        help_text="Chapter to which the video belongs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="learncraft.chapter",
                        verbose_name="Chapter",
                    ),
                ),
            ],
        ),
    ]
