# Generated by Django 5.1.2 on 2024-10-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learncraft", "0002_videoupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="icon_source",
            field=models.CharField(
                blank=True,
                help_text="Icon source of the course.",
                max_length=500,
                null=True,
                verbose_name="Icon",
            ),
        ),
    ]
