# Generated by Django 5.1.2 on 2024-10-28 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learncraft", "0004_alter_chapter_chapter_nr_alter_section_section_nr"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chapter",
            options={"ordering": ["chapter_nr"]},
        ),
        migrations.AlterModelOptions(
            name="section",
            options={"ordering": ["section_nr"]},
        ),
    ]
