# Generated by Django 5.1.2 on 2024-10-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learncraft", "0005_alter_chapter_options_alter_section_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoupload",
            name="title",
            field=models.CharField(
                default=1,
                help_text="Title of the video.",
                max_length=255,
                verbose_name="Title",
            ),
            preserve_default=False,
        ),
    ]
