# Generated by Django 5.1.2 on 2024-10-28 13:52

import course.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of the category.",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon_source",
            field=models.CharField(
                blank=True,
                help_text="Icon source of the category.",
                max_length=500,
                null=True,
                verbose_name="Icon Source",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Name of the category.",
                max_length=100,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.ForeignKey(
                default=None,
                help_text="Category to which the course belongs.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="course.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of the course.",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="folder_name",
            field=models.CharField(
                help_text="Folder name of the course.",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Folder Name",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Image of the course.",
                null=True,
                upload_to=course.models.img_upload_path,
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                default=None,
                help_text="Teacher of the course.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="course.teacher",
                verbose_name="Teacher",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(
                help_text="Title of the course.",
                max_length=100,
                unique=True,
                verbose_name="Title",
            ),
        ),
        migrations.AlterField(
            model_name="coursedoc",
            name="course",
            field=models.ForeignKey(
                default=None,
                help_text="Course to which the course doc belongs.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="course.course",
                verbose_name="Course",
            ),
        ),
        migrations.AlterField(
            model_name="coursedoc",
            name="file",
            field=models.FileField(
                blank=True,
                default=None,
                help_text="File of the course doc.",
                null=True,
                upload_to="uploads/",
                verbose_name="File",
            ),
        ),
        migrations.AlterField(
            model_name="coursedoc",
            name="sortable_inline_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Order of the course doc.", verbose_name="Order"
            ),
        ),
        migrations.AlterField(
            model_name="coursedoc",
            name="title",
            field=models.CharField(
                help_text="Title of the course doc.",
                max_length=100,
                verbose_name="Title",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                default=None,
                help_text="Course to which the lesson belongs.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="course.course",
                verbose_name="Course",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="day",
            field=models.IntegerField(
                blank=True,
                help_text="Day of the lesson.",
                null=True,
                verbose_name="Day",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="sortable_inline_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Order of the lesson.", verbose_name="Order"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="title",
            field=models.CharField(
                help_text="Title of the lesson.", max_length=100, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="url",
            field=models.CharField(
                blank=True,
                help_text="URL of the lesson.",
                max_length=500,
                null=True,
                verbose_name="URL",
            ),
        ),
    ]
